COMPONENT_ADD_INCLUDEDIRS := src src/event
COMPONENT_SRCDIRS := src

CXXFLAGS += -std=gnu++17

CPPFLAGS += \
    -DESPRESSIO_SERIAL \
    -DESPRESSIO_SERIAL_VERSION_MAJOR=0 \
    -DESPRESSIO_SERIAL_VERSION_MINOR=1 \
    -DESPRESSIO_SERIAL_VERSION_PATCH=0 \
    -DESPRESSIO_SERIAL_VERSION_STRING=\"0.1.0\"
